version: '3'

services:

  api:
    image: nginx
    restart: always
    volumes:
      - ./docker/conf/nginx/api.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443

  app:
    build: docker/php
    restart: always
    volumes:
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    depends_on:
      - api
      - db
    working_dir: /var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:9.4.26
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  pgdata:
